# Generated by Django 5.0.7 on 2024-07-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vhicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vhicle_no', models.IntegerField(unique=True)),
                ('model_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='coustmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coustmer_name', models.CharField(max_length=50)),
                ('coustmer_city', models.CharField(max_length=50, null=True)),
                ('coustmer_email', models.EmailField(max_length=254)),
                ('coustmer_no', models.ManyToManyField(to='app2.vhicle')),
            ],
        ),
    ]
