# Generated by Django 5.0.7 on 2024-07-19 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aadhar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar_no', models.IntegerField(unique=True)),
                ('created_date', models.DateField()),
                ('created_by', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str_name', models.CharField(max_length=50)),
                ('str_city', models.CharField(max_length=50, null=True)),
                ('str_email', models.EmailField(max_length=254)),
                ('aadhar_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app3.aadhar')),
            ],
        ),
    ]
